[package]
name = "bp_scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
bp_fakes = { path = "../bp_fakes" }
anyhow = "1.0.68"
buttplug = "7.1.2"
tracing = "0.1.37"
tokio = { version = "1.23.0", features = ["full", "sync"] }
tokio-util = "0.7.8"
funscript = "0.5.3"
futures = "0.3.25"